print("Введите вид животного: ", end='')
type_animal = input()
print("Укажите возраст животного: ", end='')
age_animal = input()
print("Введите кличку животного: ", end='')
name_animal = input()
print("На прием записан", type_animal, "по кличке", name_animal + ".", "Возраст:", age_animal)
